name: hundred_days_of_coding
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^0.15.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter  
  freezed: ^0.15.0+1
  lint: ^1.7.2
  

flutter:
  uses-material-design: true
